import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import { Header, Providers } from "@/components";
import { auth } from "@/auth";
import "../globals.css";
import { cn } from "@/utils";

const font = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aurora",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <Providers session={session}>
        <body className={cn("bg-default-900", font.className)}>
          <Header />
          {children}
        </body>
      </Providers>
    </html>
  );
}
